refactor main library functions

diff --git a/unix/functions b/unix/functions
--- a/unix/functions
+++ b/unix/functions
@@ -2,43 +2,43 @@
 
 # global vars
 openbsd_dev="${TEMPLATE_OPENBSD_DEV:-sd0}"
-linux_dev="${TEMPLATE_LINUX_DEV:-sda}"
+# linux_dev="${TEMPLATE_LINUX_DEV:-sda}"
 
 openbsd_disks_count() {
 	sysctl hw.disknames | tr ',' '\n' | egrep '(sd|wd)[0-9]{1}\:' | wc -l
 }
 
-linux_disks_count() {
-	fdisk -l | egrep 'Disk /dev/(sd|hd)[a-z]{1}' | wc -l
-}
+# linux_disks_count() {
+# 	fdisk -l | egrep 'Disk /dev/(sd|hd)[a-z]{1}' | wc -l
+# }
 
-linux_start_disk() {
-	local device="$1"
-	local user="$2"
+# linux_start_disk() {
+# 	local device="$1"
+# 	local user="$2"
 
-	# block device path
-	local block_dev=/dev/"$device"
+# 	# block device path
+# 	local block_dev=/dev/"$device"
 
-	# path to disk partition
-	local block_dev_partition="$block_dev"1
+# 	# path to disk partition
+# 	local block_dev_partition="$block_dev"1
 
-	# is the block device already formatted?
-	# no, so format it and configure it's contents
-	if ! blkid "$block_dev" > /dev/null; then
-		# create MBR partition table and one partition with the whole disk
-		# of the type 83 in hexcode, which means Linux type  
-		echo 'type=83' | sfdisk "$block_dev"
+# 	# is the block device already formatted?
+# 	# no, so format it and configure it's contents
+# 	if ! blkid "$block_dev" > /dev/null; then
+# 		# create MBR partition table and one partition with the whole disk
+# 		# of the type 83 in hexcode, which means Linux type  
+# 		echo 'type=83' | sfdisk "$block_dev"
 
-		# create an ext4 file system on the created partition
-		mkfs.ext4 "$block_dev_partition"
-	fi
+# 		# create an ext4 file system on the created partition
+# 		mkfs.ext4 "$block_dev_partition"
+# 	fi
 
-	# ensure mountpoiunt exists then mount
-	mkdir -p /rw/
-	mount "$block_dev_partition" /rw/
+# 	# ensure mountpoiunt exists then mount
+# 	mkdir -p /rw/
+# 	mount "$block_dev_partition" /rw/
 
-	setup_vm_disk /bin/bash "$user"
-}
+# 	setup_vm_disk /bin/bash "$user"
+# }
 
 openbsd_start_disk() {
 	# represents an empty disk uid
@@ -99,14 +99,14 @@ openbsd_main() {
 	ln -s /rw/home/* /home/
 }
 
-linux_main() {
-	local user="$1"
+# linux_main() {
+# 	local user="$1"
 
-	linux_start_disk "$linux_dev" "$user"
+# 	linux_start_disk "$linux_dev" "$user"
 
-	# make a transparent bind for user's home
-	mount --bind /rw/home/ /home/
-}
+# 	# make a transparent bind for user's home
+# 	mount --bind /rw/home/ /home/
+# }
 
 # configures default files on client disk
 setup_vm_disk() {
@@ -249,33 +249,29 @@ handle_user_config() {
 	/rw/config/rc.local
 }
 
-main() {
-	local disks_counter main_fn user	
-
-	# input argument
-	user="$1"
-
-	case "$(uname)" in
-		OpenBSD)
-			disks_counter=openbsd_disks_count
-			main_fn=openbsd_main
-
-			;;
-		*)
-			disks_counter=linux_disks_count
-			main_fn=linux_main
-			
-			;;
-	esac
-
-	if [ "$($disks_counter)" -lt 2 ]; then
-		echo "[-] seems like the template vm here, aborting..."
+on_template_or_out() {
+	if [ "$1" -lt 2 ]; then
+		info "seems like the template vm here, aborting..."
 		exit 0
 	fi
+}
 
-	# call arbitrary main function
-	$main_fn "$user"
+info() {
+	echo "$(date) [INFO] $@"
+}
+
+err() {
+	echo "$(date) [ERROR] $@"
+}
+
+templated_exec() {	
+	# input argument
+	main=$1
+	log="${2:-/var/log/templated.log}"
+
+	info "starting templated main function" > "$log"
+	main > "$log" 2>&1
 
 	# apply user custom configuration
-	handle_user_config
+	handle_user_config > "$log" 2>&1
 }
