abstract detection functionality

diff --git a/unix/functions b/unix/functions
--- a/unix/functions
+++ b/unix/functions
@@ -194,6 +194,55 @@ start_user_custom_config() {
 	exec_log "calling user rc script" "$rw_dir"/config/rc.local
 }
 
+ensure_formated_and_mounted() {
+	local env_device
+	env_device="${TEMPLATED_DEV}"
+
+	if [ -n "$env_device" ]; then
+		start_disk "$env_device" "$@"
+		return
+	fi
+
+	local uuid uuid_count disk disk_count
+	uuid="$(detect_partition)"
+	disk="$(detect_raw_disk)"
+
+	# nothing detected
+	if [ -z "$disk" ] && [ -z "$uuid" ]; then
+		err "any raw disk or partition available"
+		return "$format_disk_err"
+	fi
+
+	# count lines
+	uuid_count="$(wc -l <<< "${uuid}")"
+	disk_count="$(wc -l <<< "${disk}")"
+
+	local disk_valid uuid_valid
+	disk_valid=false
+	uuid_valid=false
+
+	# set whether valid
+	[ -n "$disk" ] && [ "$disk_count" -eq 1 ] && disk_valid=true
+	[ -n "$uuid" ] && [ "$uuid_count" -eq 1 ] && uuid_valid=true
+
+	if ! $disk_valid && ! $uuid_valid; then
+		err "can not proceed, unable to detect with precision which device to use"
+		info "ensure that only exists 1 formatted partition or 1 disk"
+		return "$format_disk_err"
+	fi
+
+	# takes precedence over the raw disk.
+	# this is a must, because one should be able to start a template-based 
+	# vm with just some raw disk and it ignores these raw disks
+	if $uuid_valid; then
+		start_disk_from_partition "$uuid" "$@"
+		return
+	fi
+	
+	# disk is raw, will use the first partition
+	start_disk "$disk" -B "$disk"1 "$@"
+}
+
 is_template_vm() {
 	if [ "$1" -lt 2 ]; then
 		info "seems like the template vm here, aborting..."
